### ISSUE TITLE
You can write this MUCH BETTER

### ISSUE THREAD

**Issue by LuziferSenpai** [SkywardRay/StackSizeCombinator#1]
Hey,

what YOU could do is, remove the GUI completly. Then take every Input the Combinator gets look if its a Item, look whats the max stack value of that Item and Output then the Max Stack Value. For the Non Items you just Output the Input Value. So you can use Two Constant Combintors instead of the Arithmetic Combinator

**Comment by SkywardRay** [comment]
I suppose it's possible to remove the current GUI and maybe make one myself. But the GUI is the only thing I don't like about the current solution. 

Anyway, I spent 10 hours on it in the last 2 days learning about modding and finding out how to get everything working in the first place. So maybe I'll try it with some different entities later.

If anyone else wants to write this MUCH BETTER I'll be happy to look at pull requests.

**Comment by LuziferSenpai** [comment]
Look into my Wireless Circuit Network MOD on the MOD Portal, there you see how to make Constant Combinators work and how to remove/add GUI.

**Comment by SkywardRay** [comment]
I've taken a look at your mod, very nicely structured code. Thanks for pointing it out. I'm definitely going to take some time to change the GUI, soon.
